# Generated by Django 3.2.6 on 2021-08-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prod_date', models.DateTimeField(verbose_name='date published')),
                ('price', models.FloatField()),
            ],
        ),
    ]
